### ISSUE TITLE
AES-GCM broken in Edge/IE11, is there any way to resolve this problem?

### ISSUE THREAD

**Issue by AJLoveChina** [rndme/aes4js#2]
As title, Edge /IE11 seems to support `crypto` api, but `AES-GCM` broken when I  tested.

Error info : 8070000b

And some people also say that `aes-gcm` could be not supported in Edge/IE11.
* https://openpgpjs.org/openpgpjs/doc/crypto_gcm.js.html
* https://twitter.com/paul_reviews/status/664241000605458432?lang=en 

I am not good at `crypto`, but I think pure javascript code that doesn't rely on `crypto` could also encrypt / decrypt in `aes-gcm` mode ? Is that right?

Do you have any idea?

Thanks,
AJLoveChina

**Comment by AJLoveChina** [comment]
https://stackoverflow.com/questions/42933162/web-crypto-api-using-microsoft-edge-38-14393-0-0

![image](https://user-images.githubusercontent.com/11222746/79631327-394ce780-818b-11ea-8d6e-d42ae432caec.png)

**Comment by rndme** [comment]
I've tested recently and it's working in edge. I  don't have the ability to test in IE11. While IE11 could get a crypto polyfill to make this work, adding an AES routine would severally complicate and expand the package, making it harder to reason about and analyze. Since IE11 is dead, I'm closing this, but do thank you for reaching out.
